services:
  # MariaDB服务
  mariadb:
    # Switched to MariaDB
    image: mariadb:11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=aoa
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    # ports:
    #   - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./init_sql:/docker-entrypoint-initdb.d
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-connect='SET NAMES utf8mb4'
      - --innodb-flush-log-at-trx-commit=0
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "--password=123456"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Redis服务
  redis:
    image: redis:latest
    restart: always
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # 后端服务
  backend:
    image: "polymatrix/aoa-mvp-backend"
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./data/uploads:/app/uploads
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mariadb:3306/aoa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_REDIS_HOST=redis

  # 前端服务
  frontend:
    image: "polymatrix/aoa-mvp-frontend"
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "8081:80"
